### ISSUE TITLE
Android 15+ 16KB page size

### ISSUE THREAD

**Issue by SZGarmin** [atteneder/DracoUnity#79]
Hey

I'm using DracoUnity in a Unity app where Android is one of the build targets.
Recently I switched to the latest Unity 6 version (6000.0.48f1) which prints the following warning during the build process:

**Plugin 'Assets/External/com.atteneder.draco/Runtime/Plugins/Android/libs/arm64-v8a/libdracodec_unity.so' is not 16KB-aligned. This may cause issues on ARM64 devices running Android 15+.
More info: https://developer.android.com/guide/practices/page-sizes.**

I wasn't aware of this new requirement and I thought I should point this out before it becomes a problem for users of this library.

Since I guess you are quite busy, I want to ask where I can find the sources for the native libs of DracoUnity 4.1.0, so I can recompile with 16k page size. Is it this repo? https://github.com/atteneder/draco

Thanks

**Comment by atteneder** [comment]
Thanks for your patience. This has been fixed in [Draco for Unity 5.2.0](https://docs.unity3d.com/Packages/com.unity.cloud.draco@5.2/changelog/CHANGELOG.html#520---2025-08-19).

> [!NOTE]  
> Updating the package will trigger a compiler warning in current glTFast versions. This warning is harmless and will be removed in the upcoming release.

**Comment by AhmadMansy** [comment]
> Thanks for your patience. This has been fixed in [Draco for Unity 5.2.0](https://docs.unity3d.com/Packages/com.unity.cloud.draco@5.2/changelog/CHANGELOG.html#520---2025-08-19).
> 
> Note
> 
> Updating the package will trigger a compiler warning in current glTFast versions. This warning is harmless and will be removed in the upcoming release.

Is this the compiler warning that you mentioned?
because this the draco 5.2.0 version and still showing that 16KB is not supported
<img width="716" height="51" alt="Image" src="https://github.com/user-attachments/assets/38b32cfc-51a5-454d-98d1-ccbec3ec3e2e" />

**Comment by atteneder** [comment]
> Is this the compiler warning that you mentioned? because this the draco 5.2.0 version and still showing that 16KB is not supported <img alt="Image" width="716" height="51" src="https://private-user-images.githubusercontent.com/54113248/484140636-38b32cfc-51a5-454d-98d1-ccbec3ec3e2e.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTY3MjI0NjgsIm5iZiI6MTc1NjcyMjE2OCwicGF0aCI6Ii81NDExMzI0OC80ODQxNDA2MzYtMzhiMzJjZmMtNTFhNS00NTRkLTk4ZDEtY2NiZWMzZWMzZTJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA5MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwOTAxVDEwMjI0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwNWFjODg4NTAwMDQ2NTFiNTllNGE2ODg2YzI4YjA3MmMzMDFlOTEwODg0MDQ4YmYxMmRkZGRiMThlZmNmOTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vWReES68Ju0IMadW5mkAuxP_Z-4QgogrbkonjLPXFK4">


No, that's a different error.

How did you install Draco for Unity 5.2.0? It seems like you don't use version 5.2.0 and not installing via the package manager.

I just installed it via package manager and confirmed that the binaries are 16kB compatible (following the [official guide](https://developer.android.com/guide/practices/page-sizes)):


```shell
llvm-objdump -p Library/PackageCache/com.unity.cloud.draco@4b657c9cdeaa/Runtime/Plugins/Android/libs/arm64-v8a/libdraco_unity.so | grep LOAD
    LOAD off    0x0000000000000000 vaddr 0x0000000000000000 paddr 0x0000000000000000 align 2**14
    LOAD off    0x00000000001ee060 vaddr 0x00000000001f2060 paddr 0x00000000001f2060 align 2**14
    LOAD off    0x00000000001fb720 vaddr 0x0000000000203720 paddr 0x0000000000203720 align 2**14
```

**Comment by AhmadMansy** [comment]
> > Is this the compiler warning that you mentioned? because this the draco 5.2.0 version and still showing that 16KB is not supported <img alt="Image" width="716" height="51" src="https://private-user-images.githubusercontent.com/54113248/484140636-38b32cfc-51a5-454d-98d1-ccbec3ec3e2e.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTY3MjI0NjgsIm5iZiI6MTc1NjcyMjE2OCwicGF0aCI6Ii81NDExMzI0OC80ODQxNDA2MzYtMzhiMzJjZmMtNTFhNS00NTRkLTk4ZDEtY2NiZWMzZWMzZTJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA5MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwOTAxVDEwMjI0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwNWFjODg4NTAwMDQ2NTFiNTllNGE2ODg2YzI4YjA3MmMzMDFlOTEwODg0MDQ4YmYxMmRkZGRiMThlZmNmOTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vWReES68Ju0IMadW5mkAuxP_Z-4QgogrbkonjLPXFK4">
> 
> No, that's a different error.
> 
> How did you install Draco for Unity 5.2.0? It seems like you don't use version 5.2.0 and not installing via the package manager.
> 
> I just installed it via package manager and confirmed that the binaries are 16kB compatible (following the [official guide](https://developer.android.com/guide/practices/page-sizes)):
> 
> llvm-objdump -p Library/PackageCache/com.unity.cloud.draco@4b657c9cdeaa/Runtime/Plugins/Android/libs/arm64-v8a/libdraco_unity.so | grep LOAD
>     LOAD off    0x0000000000000000 vaddr 0x0000000000000000 paddr 0x0000000000000000 align 2**14
>     LOAD off    0x00000000001ee060 vaddr 0x00000000001f2060 paddr 0x00000000001f2060 align 2**14
>     LOAD off    0x00000000001fb720 vaddr 0x0000000000203720 paddr 0x0000000000203720 align 2**14



I am using Draco 5.2 installed via package manager
Will try again in a clean project and see (I am using Unity 2022.3.62)
<img width="419" height="129" alt="Image" src="https://github.com/user-attachments/assets/8d2525ac-bcff-435a-950d-af9a47281d54" />

**Comment by AhmadMansy** [comment]
The warning didn't appear with a clean project. However, still have it with my project
deleted both folders her /Users/[MY-NAME]/Library/Unity/cache and UnityProject/Packages and still no luck


`Plugin 'Packages/com.unity.cloud.draco/Runtime/Plugins/Android/libs/arm64-v8a/libdraco_unity.so' is not 16KB-aligned. This may cause issues on ARM64 devices running Android 15+.
More info: https://developer.android.com/guide/practices/page-sizes.
System.Linq.Enumerable/WhereEnumerableIterator`1<object>:MoveNext ()
Bee.BeeDriver.BeeDriver:WriteDataForBuildProgram (Bee.BeeDriver.InternalState,System.Threading.Tasks.TaskCompletionSource`1<int>) (at /Users/bokken/build/output/unity/unity/Tools/Bee/Bee.BeeDriver2/BeeDriver.cs:100)
Bee.BeeDriver.BeeDriver/<>c__DisplayClass0_0:<BuildAsync>g__WriteData|0 () (at /Users/bokken/build/output/unity/unity/Tools/Bee/Bee.BeeDriver2/BeeDriver.cs:75)
Bee.BeeDriver.BeeDriver:BuildAsync (Bee.BeeDriver.BuildRequest,System.Threading.CancellationToken) (at /Users/bokken/build/output/unity/unity/Tools/Bee/Bee.BeeDriver2/BeeDriver.cs:78)
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&) (at /Users/bokken/build/output/unity/unity/Modules/IMGUI/GUIUtility.cs:203)
`

I noticed this Users/bokken/ which is not a user folder on my machine

will try a different machine and see

**Comment by AhmadMansy** [comment]
@atteneder Hi

I found the issue.
I compared the checksum for libdraco_unity.so in the output and here https://packages.unity.com/com.unity.cloud.draco/-/com.unity.cloud.draco-5.2.0.tgz

they are the same.

22,776,864 bytes arm64-v8a/libdraco_unity.so
checksum: 61ea688c6675f60add8bffaed018ecc45e2317f2bf0bc345d942e70f615bac04

18,877,832 bytes armeabi-v7a/libdraco_unity.so
checksum: 0eff425d0687fb53f6542026f7906539db3a1df33ecb8d22b91eb4d25a02de54


the empty project didn't have this issue because it was targeting only ARMv7 architecture, but choosing both ARMv7 and ARM64 will show the warning.
<img width="1021" height="308" alt="Image" src="https://github.com/user-attachments/assets/725389c9-dc7d-4c46-b12d-a1f22019dbde" />

here is an empty project with both architectures targeted

[demo-project-with-draco5.2.zip](https://github.com/user-attachments/files/22079905/demo-project-with-draco5.2.zip)

<img width="318" height="77" alt="Image" src="https://github.com/user-attachments/assets/c1a80467-46eb-41a8-9831-81df8db3805f" />

**Comment by atteneder** [comment]
I was able to reproduce and fix the message.

It's a warning that gets logged during build, but still leads to a successful build, so not blocking you from releasing, right?

The binary itself is 16kB compatible, but for some reason Unity's meta file does not reflect that properly. The fix is already in the pipe.

Thanks for reporting!

**Comment by AhmadMansy** [comment]
> I was able to reproduce and fix the message.
> 
> It's a warning that gets logged during build, but still leads to a successful build, so not blocking you from releasing, right?
> 
> The binary itself is 16kB compatible, but for some reason Unity's meta file does not reflect that properly. The fix is already in the pipe.
> 
> Thanks for reporting!

Thank you for your reply, and yes I can release and this is not a blocker for now.

However, since I release for both architecture, Android has two library files, one of them is not 16kb compatible - the one under armeabi-v7a (I tested the apk).

Thank you again for your reply and your time, and will wait for the fix
